### PR TITLE
Fixed #13 Django 1.8 warning

### LINKED ISSUE #13: Django 1.8 deprecarted warnings
When I use that package in my `Django 1.8.4` project I get these warnings:

```
/home/linch/.pyenv/versions/metrophysics/lib/python3.4/site-packages/class_based_auth_views/views.py:63: RemovedInDjango19Warning: `request.REQUEST` is deprecated, use `request.GET` or `request.POST` instead.
  redirect_to = self.request.REQUEST.get(self.redirect_field_name, '')

/home/linch/.pyenv/versions/metrophysics/lib/python3.4/site-packages/django/core/handlers/wsgi.py:126: RemovedInDjango19Warning: `MergeDict` is deprecated, use `dict.update()` instead.
  self._request = datastructures.MergeDict(self.POST, self.GET)
```

If you want, I can fork repository and fix theses warnings.

Thanks.

### PR DESCRIPTION
**Pull request by LukasRychtecky**

### CODE REVIEW

**Comment by LukasRychtecky** [comment]
I've tested on my project with Django 1.8 and Python 3.4

**Comment by LukasRychtecky** [comment]
Could you comment or merge this?

**Comment by PetrDlouhy** [comment]
I realized, that this PR is incorrect and breaks the next redirect function. Use PR #16, please.

**Comment by cyberstar** [comment]
@LukasRychtecky Hi! thanks for your PR! Unfortunately I have to fix it. The issue is fixed in https://github.com/stefanfoulis/django-class-based-auth-views/pull/17

**Pull request closed without merging**
